# Generated by Django 4.1.3 on 2022-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_cartitems_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='instamojo_id',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
