# Generated by Django 4.1.3 on 2022-11-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_cart_instamojo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pizzacategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
